/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const EVENT_CONFIG_DISCRIMINATOR = new Uint8Array([
  85, 63, 74, 243, 198, 192, 138, 0,
]);

export function getEventConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EVENT_CONFIG_DISCRIMINATOR
  );
}

export type EventConfig = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  maxSupply: number;
  ticketsMinted: number;
  resaleCapBps: number;
  eventName: string;
  eventLocation: string;
  eventDescription: string;
  maxTicketsPerPerson: number;
  eventTimestamp: bigint;
  createdAt: bigint;
  updatedAt: bigint;
  bump: number;
};

export type EventConfigArgs = {
  authority: Address;
  maxSupply: number;
  ticketsMinted: number;
  resaleCapBps: number;
  eventName: string;
  eventLocation: string;
  eventDescription: string;
  maxTicketsPerPerson: number;
  eventTimestamp: number | bigint;
  createdAt: number | bigint;
  updatedAt: number | bigint;
  bump: number;
};

export function getEventConfigEncoder(): Encoder<EventConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['authority', getAddressEncoder()],
      ['maxSupply', getU32Encoder()],
      ['ticketsMinted', getU32Encoder()],
      ['resaleCapBps', getU32Encoder()],
      ['eventName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      [
        'eventLocation',
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
      ],
      [
        'eventDescription',
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
      ],
      ['maxTicketsPerPerson', getU8Encoder()],
      ['eventTimestamp', getI64Encoder()],
      ['createdAt', getI64Encoder()],
      ['updatedAt', getI64Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: EVENT_CONFIG_DISCRIMINATOR })
  );
}

export function getEventConfigDecoder(): Decoder<EventConfig> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['authority', getAddressDecoder()],
    ['maxSupply', getU32Decoder()],
    ['ticketsMinted', getU32Decoder()],
    ['resaleCapBps', getU32Decoder()],
    ['eventName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['eventLocation', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    [
      'eventDescription',
      addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder()),
    ],
    ['maxTicketsPerPerson', getU8Decoder()],
    ['eventTimestamp', getI64Decoder()],
    ['createdAt', getI64Decoder()],
    ['updatedAt', getI64Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getEventConfigCodec(): Codec<EventConfigArgs, EventConfig> {
  return combineCodec(getEventConfigEncoder(), getEventConfigDecoder());
}

export function decodeEventConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<EventConfig, TAddress>;
export function decodeEventConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<EventConfig, TAddress>;
export function decodeEventConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<EventConfig, TAddress> | MaybeAccount<EventConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getEventConfigDecoder()
  );
}

export async function fetchEventConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<EventConfig, TAddress>> {
  const maybeAccount = await fetchMaybeEventConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeEventConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<EventConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeEventConfig(maybeAccount);
}

export async function fetchAllEventConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<EventConfig>[]> {
  const maybeAccounts = await fetchAllMaybeEventConfig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeEventConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<EventConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeEventConfig(maybeAccount));
}
