/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getListingStatusDecoder,
  getListingStatusEncoder,
  type ListingStatus,
  type ListingStatusArgs,
} from '../types';

export const LISTING_DISCRIMINATOR = new Uint8Array([
  218, 32, 50, 73, 43, 134, 26, 58,
]);

export function getListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(LISTING_DISCRIMINATOR);
}

export type Listing = {
  discriminator: ReadonlyUint8Array;
  /** Seller who receives payment */
  seller: Address;
  /** The ticket being sold (commitment proves ownership) */
  ticketCommitment: ReadonlyUint8Array;
  /**
   * Encrypted secret: secret XOR hash(listing_pda)
   * Allows seller to prove ownership without revealing secret
   */
  encryptedSecret: ReadonlyUint8Array;
  /** Sale price in lamports */
  priceLamports: bigint;
  /** Which event this ticket belongs to */
  eventConfig: Address;
  /** Which ticket ID within the event */
  ticketId: number;
  /** Claim data */
  buyer: Option<Address>;
  buyerCommitment: Option<ReadonlyUint8Array>;
  claimedAt: Option<bigint>;
  /** Current status of the listing */
  status: ListingStatus;
  /** When the listing was created */
  createdAt: bigint;
  /** PDA bump for listing address derivation */
  bump: number;
};

export type ListingArgs = {
  /** Seller who receives payment */
  seller: Address;
  /** The ticket being sold (commitment proves ownership) */
  ticketCommitment: ReadonlyUint8Array;
  /**
   * Encrypted secret: secret XOR hash(listing_pda)
   * Allows seller to prove ownership without revealing secret
   */
  encryptedSecret: ReadonlyUint8Array;
  /** Sale price in lamports */
  priceLamports: number | bigint;
  /** Which event this ticket belongs to */
  eventConfig: Address;
  /** Which ticket ID within the event */
  ticketId: number;
  /** Claim data */
  buyer: OptionOrNullable<Address>;
  buyerCommitment: OptionOrNullable<ReadonlyUint8Array>;
  claimedAt: OptionOrNullable<number | bigint>;
  /** Current status of the listing */
  status: ListingStatusArgs;
  /** When the listing was created */
  createdAt: number | bigint;
  /** PDA bump for listing address derivation */
  bump: number;
};

export function getListingEncoder(): Encoder<ListingArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['seller', getAddressEncoder()],
      ['ticketCommitment', fixEncoderSize(getBytesEncoder(), 32)],
      ['encryptedSecret', fixEncoderSize(getBytesEncoder(), 32)],
      ['priceLamports', getU64Encoder()],
      ['eventConfig', getAddressEncoder()],
      ['ticketId', getU32Encoder()],
      ['buyer', getOptionEncoder(getAddressEncoder())],
      [
        'buyerCommitment',
        getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32)),
      ],
      ['claimedAt', getOptionEncoder(getI64Encoder())],
      ['status', getListingStatusEncoder()],
      ['createdAt', getI64Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: LISTING_DISCRIMINATOR })
  );
}

export function getListingDecoder(): Decoder<Listing> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['seller', getAddressDecoder()],
    ['ticketCommitment', fixDecoderSize(getBytesDecoder(), 32)],
    ['encryptedSecret', fixDecoderSize(getBytesDecoder(), 32)],
    ['priceLamports', getU64Decoder()],
    ['eventConfig', getAddressDecoder()],
    ['ticketId', getU32Decoder()],
    ['buyer', getOptionDecoder(getAddressDecoder())],
    [
      'buyerCommitment',
      getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32)),
    ],
    ['claimedAt', getOptionDecoder(getI64Decoder())],
    ['status', getListingStatusDecoder()],
    ['createdAt', getI64Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getListingCodec(): Codec<ListingArgs, Listing> {
  return combineCodec(getListingEncoder(), getListingDecoder());
}

export function decodeListing<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Listing, TAddress>;
export function decodeListing<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Listing, TAddress>;
export function decodeListing<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Listing, TAddress> | MaybeAccount<Listing, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getListingDecoder()
  );
}

export async function fetchListing<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Listing, TAddress>> {
  const maybeAccount = await fetchMaybeListing(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeListing<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Listing, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeListing(maybeAccount);
}

export async function fetchAllListing(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Listing>[]> {
  const maybeAccounts = await fetchAllMaybeListing(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeListing(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Listing>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeListing(maybeAccount));
}
