/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type EventUpdated = {
  eventConfig: Address;
  authority: Address;
  resaleCapBps: number;
};

export type EventUpdatedArgs = EventUpdated;

export function getEventUpdatedEncoder(): FixedSizeEncoder<EventUpdatedArgs> {
  return getStructEncoder([
    ['eventConfig', getAddressEncoder()],
    ['authority', getAddressEncoder()],
    ['resaleCapBps', getU32Encoder()],
  ]);
}

export function getEventUpdatedDecoder(): FixedSizeDecoder<EventUpdated> {
  return getStructDecoder([
    ['eventConfig', getAddressDecoder()],
    ['authority', getAddressDecoder()],
    ['resaleCapBps', getU32Decoder()],
  ]);
}

export function getEventUpdatedCodec(): FixedSizeCodec<
  EventUpdatedArgs,
  EventUpdated
> {
  return combineCodec(getEventUpdatedEncoder(), getEventUpdatedDecoder());
}
