/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EventCreated = {
  eventConfig: Address;
  authority: Address;
  maxSupply: number;
  resaleCapBps: number;
  eventName: string;
  eventLocation: string;
  eventDescription: string;
  maxTicketsPerPerson: number;
  eventTimestamp: bigint;
};

export type EventCreatedArgs = {
  eventConfig: Address;
  authority: Address;
  maxSupply: number;
  resaleCapBps: number;
  eventName: string;
  eventLocation: string;
  eventDescription: string;
  maxTicketsPerPerson: number;
  eventTimestamp: number | bigint;
};

export function getEventCreatedEncoder(): Encoder<EventCreatedArgs> {
  return getStructEncoder([
    ['eventConfig', getAddressEncoder()],
    ['authority', getAddressEncoder()],
    ['maxSupply', getU32Encoder()],
    ['resaleCapBps', getU32Encoder()],
    ['eventName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['eventLocation', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    [
      'eventDescription',
      addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
    ],
    ['maxTicketsPerPerson', getU8Encoder()],
    ['eventTimestamp', getI64Encoder()],
  ]);
}

export function getEventCreatedDecoder(): Decoder<EventCreated> {
  return getStructDecoder([
    ['eventConfig', getAddressDecoder()],
    ['authority', getAddressDecoder()],
    ['maxSupply', getU32Decoder()],
    ['resaleCapBps', getU32Decoder()],
    ['eventName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['eventLocation', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    [
      'eventDescription',
      addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder()),
    ],
    ['maxTicketsPerPerson', getU8Decoder()],
    ['eventTimestamp', getI64Decoder()],
  ]);
}

export function getEventCreatedCodec(): Codec<EventCreatedArgs, EventCreated> {
  return combineCodec(getEventCreatedEncoder(), getEventCreatedDecoder());
}
