/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum ListingStatus {
  Active,
  Claimed,
  Completed,
  Cancelled,
}

export type ListingStatusArgs = ListingStatus;

export function getListingStatusEncoder(): FixedSizeEncoder<ListingStatusArgs> {
  return getEnumEncoder(ListingStatus);
}

export function getListingStatusDecoder(): FixedSizeDecoder<ListingStatus> {
  return getEnumDecoder(ListingStatus);
}

export function getListingStatusCodec(): FixedSizeCodec<
  ListingStatusArgs,
  ListingStatus
> {
  return combineCodec(getListingStatusEncoder(), getListingStatusDecoder());
}
