/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/**
 * Nullifier account - prevents double-spending of tickets.
 *
 * This is an empty struct - existence is the proof.
 * When a ticket is transferred:
 * 1. Compute nullifier_seed = hash("nullifier" || seller_secret)
 * 2. CREATE nullifier account at derived address
 * 3. If address already exists → transfer fails (double-spend prevented)
 *
 * The nullifier is derived from the seller's secret, which is unique per ticket.
 */
export type Nullifier = {};

export type NullifierArgs = Nullifier;

export function getNullifierEncoder(): FixedSizeEncoder<NullifierArgs> {
  return getStructEncoder([]);
}

export function getNullifierDecoder(): FixedSizeDecoder<Nullifier> {
  return getStructDecoder([]);
}

export function getNullifierCodec(): FixedSizeCodec<NullifierArgs, Nullifier> {
  return combineCodec(getNullifierEncoder(), getNullifierDecoder());
}
