/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from '@solana/kit';

/**
 * Private ticket stored as compressed account.
 *
 * Privacy: `owner_commitment` hides who owns the ticket.
 * Only the owner (who knows their secret) can prove ownership.
 *
 * Commitment = hash(owner_pubkey || secret)
 * - owner_pubkey: The actual owner's public key
 * - secret: Derived from wallet signature, unique per ticket
 */
export type PrivateTicket = {
  /** Link to parent event */
  eventConfig: Address;
  /** Unique ticket identifier within the event */
  ticketId: number;
  /**
   * Owner commitment: hash(owner_pubkey || secret)
   * Only the owner who knows their secret can prove ownership.
   * Secret is derived from: hash(wallet_sign("ticket:{ticket_id}:{event_config}"))
   */
  ownerCommitment: ReadonlyUint8Array;
  /** Original mint price (public for resale cap calculation) */
  originalPrice: bigint;
};

export type PrivateTicketArgs = {
  /** Link to parent event */
  eventConfig: Address;
  /** Unique ticket identifier within the event */
  ticketId: number;
  /**
   * Owner commitment: hash(owner_pubkey || secret)
   * Only the owner who knows their secret can prove ownership.
   * Secret is derived from: hash(wallet_sign("ticket:{ticket_id}:{event_config}"))
   */
  ownerCommitment: ReadonlyUint8Array;
  /** Original mint price (public for resale cap calculation) */
  originalPrice: number | bigint;
};

export function getPrivateTicketEncoder(): FixedSizeEncoder<PrivateTicketArgs> {
  return getStructEncoder([
    ['eventConfig', getAddressEncoder()],
    ['ticketId', getU32Encoder()],
    ['ownerCommitment', fixEncoderSize(getBytesEncoder(), 32)],
    ['originalPrice', getU64Encoder()],
  ]);
}

export function getPrivateTicketDecoder(): FixedSizeDecoder<PrivateTicket> {
  return getStructDecoder([
    ['eventConfig', getAddressDecoder()],
    ['ticketId', getU32Decoder()],
    ['ownerCommitment', fixDecoderSize(getBytesDecoder(), 32)],
    ['originalPrice', getU64Decoder()],
  ]);
}

export function getPrivateTicketCodec(): FixedSizeCodec<
  PrivateTicketArgs,
  PrivateTicket
> {
  return combineCodec(getPrivateTicketEncoder(), getPrivateTicketDecoder());
}
