/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type SaleCompleted = {
  listing: Address;
  seller: Address;
  buyer: Address;
  eventConfig: Address;
  ticketId: number;
  priceLamports: bigint;
};

export type SaleCompletedArgs = {
  listing: Address;
  seller: Address;
  buyer: Address;
  eventConfig: Address;
  ticketId: number;
  priceLamports: number | bigint;
};

export function getSaleCompletedEncoder(): FixedSizeEncoder<SaleCompletedArgs> {
  return getStructEncoder([
    ['listing', getAddressEncoder()],
    ['seller', getAddressEncoder()],
    ['buyer', getAddressEncoder()],
    ['eventConfig', getAddressEncoder()],
    ['ticketId', getU32Encoder()],
    ['priceLamports', getU64Encoder()],
  ]);
}

export function getSaleCompletedDecoder(): FixedSizeDecoder<SaleCompleted> {
  return getStructDecoder([
    ['listing', getAddressDecoder()],
    ['seller', getAddressDecoder()],
    ['buyer', getAddressDecoder()],
    ['eventConfig', getAddressDecoder()],
    ['ticketId', getU32Decoder()],
    ['priceLamports', getU64Decoder()],
  ]);
}

export function getSaleCompletedCodec(): FixedSizeCodec<
  SaleCompletedArgs,
  SaleCompleted
> {
  return combineCodec(getSaleCompletedEncoder(), getSaleCompletedDecoder());
}
