/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type TicketTransferred = { eventConfig: Address };

export type TicketTransferredArgs = TicketTransferred;

export function getTicketTransferredEncoder(): FixedSizeEncoder<TicketTransferredArgs> {
  return getStructEncoder([['eventConfig', getAddressEncoder()]]);
}

export function getTicketTransferredDecoder(): FixedSizeDecoder<TicketTransferred> {
  return getStructDecoder([['eventConfig', getAddressDecoder()]]);
}

export function getTicketTransferredCodec(): FixedSizeCodec<
  TicketTransferredArgs,
  TicketTransferred
> {
  return combineCodec(
    getTicketTransferredEncoder(),
    getTicketTransferredDecoder()
  );
}
