/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type TicketMinted = { eventConfig: Address; purchasePrice: bigint };

export type TicketMintedArgs = {
  eventConfig: Address;
  purchasePrice: number | bigint;
};

export function getTicketMintedEncoder(): FixedSizeEncoder<TicketMintedArgs> {
  return getStructEncoder([
    ['eventConfig', getAddressEncoder()],
    ['purchasePrice', getU64Encoder()],
  ]);
}

export function getTicketMintedDecoder(): FixedSizeDecoder<TicketMinted> {
  return getStructDecoder([
    ['eventConfig', getAddressDecoder()],
    ['purchasePrice', getU64Decoder()],
  ]);
}

export function getTicketMintedCodec(): FixedSizeCodec<
  TicketMintedArgs,
  TicketMinted
> {
  return combineCodec(getTicketMintedEncoder(), getTicketMintedDecoder());
}
