/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCancelListingInstruction,
  type ParsedClaimListingInstruction,
  type ParsedCompleteSaleInstruction,
  type ParsedCreateEventInstruction,
  type ParsedCreateListingInstruction,
  type ParsedMintTicketInstruction,
  type ParsedReleaseClaimInstruction,
  type ParsedTransferTicketInstruction,
  type ParsedUpdateEventInstruction,
} from '../instructions';

export const ENCORE_PROGRAM_ADDRESS =
  'BjapcaBemidgideMDLWX4wujtnEETZknmNyv28uXVB7V' as Address<'BjapcaBemidgideMDLWX4wujtnEETZknmNyv28uXVB7V'>;

export enum EncoreAccount {
  EventConfig,
  Listing,
}

export function identifyEncoreAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): EncoreAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([85, 63, 74, 243, 198, 192, 138, 0])
      ),
      0
    )
  ) {
    return EncoreAccount.EventConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([218, 32, 50, 73, 43, 134, 26, 58])
      ),
      0
    )
  ) {
    return EncoreAccount.Listing;
  }
  throw new Error(
    'The provided account could not be identified as a encore account.'
  );
}

export enum EncoreInstruction {
  CancelListing,
  ClaimListing,
  CompleteSale,
  CreateEvent,
  CreateListing,
  MintTicket,
  ReleaseClaim,
  TransferTicket,
  UpdateEvent,
}

export function identifyEncoreInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): EncoreInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([41, 183, 50, 232, 230, 233, 157, 70])
      ),
      0
    )
  ) {
    return EncoreInstruction.CancelListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([96, 238, 149, 85, 208, 136, 248, 158])
      ),
      0
    )
  ) {
    return EncoreInstruction.ClaimListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([212, 87, 122, 108, 63, 103, 44, 185])
      ),
      0
    )
  ) {
    return EncoreInstruction.CompleteSale;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([49, 219, 29, 203, 22, 98, 100, 87])
      ),
      0
    )
  ) {
    return EncoreInstruction.CreateEvent;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([18, 168, 45, 24, 191, 31, 117, 54])
      ),
      0
    )
  ) {
    return EncoreInstruction.CreateListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([159, 167, 223, 60, 138, 6, 23, 29])
      ),
      0
    )
  ) {
    return EncoreInstruction.MintTicket;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([109, 194, 80, 47, 30, 93, 16, 253])
      ),
      0
    )
  ) {
    return EncoreInstruction.ReleaseClaim;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([191, 184, 74, 239, 164, 172, 188, 32])
      ),
      0
    )
  ) {
    return EncoreInstruction.TransferTicket;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([70, 108, 211, 125, 171, 176, 25, 217])
      ),
      0
    )
  ) {
    return EncoreInstruction.UpdateEvent;
  }
  throw new Error(
    'The provided instruction could not be identified as a encore instruction.'
  );
}

export type ParsedEncoreInstruction<
  TProgram extends string = 'BjapcaBemidgideMDLWX4wujtnEETZknmNyv28uXVB7V',
> =
  | ({
      instructionType: EncoreInstruction.CancelListing;
    } & ParsedCancelListingInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.ClaimListing;
    } & ParsedClaimListingInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.CompleteSale;
    } & ParsedCompleteSaleInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.CreateEvent;
    } & ParsedCreateEventInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.CreateListing;
    } & ParsedCreateListingInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.MintTicket;
    } & ParsedMintTicketInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.ReleaseClaim;
    } & ParsedReleaseClaimInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.TransferTicket;
    } & ParsedTransferTicketInstruction<TProgram>)
  | ({
      instructionType: EncoreInstruction.UpdateEvent;
    } & ParsedUpdateEventInstruction<TProgram>);
