/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';

/** InvalidTicketSupply: Ticket supply must be greater than zero */
export const ENCORE_ERROR__INVALID_TICKET_SUPPLY = 0x1770; // 6000
/** TicketSupplyTooLarge: Ticket supply exceeds maximum allowed */
export const ENCORE_ERROR__TICKET_SUPPLY_TOO_LARGE = 0x1771; // 6001
/** ResaleCapTooLow: Resale cap must be at least 1.0x (10000 basis points) */
export const ENCORE_ERROR__RESALE_CAP_TOO_LOW = 0x1772; // 6002
/** ResaleCapTooHigh: Resale cap exceeds maximum allowed (10.0x) */
export const ENCORE_ERROR__RESALE_CAP_TOO_HIGH = 0x1773; // 6003
/** EventNameTooLong: Event name exceeds maximum length */
export const ENCORE_ERROR__EVENT_NAME_TOO_LONG = 0x1774; // 6004
/** EventLocationTooLong: Event location exceeds maximum length */
export const ENCORE_ERROR__EVENT_LOCATION_TOO_LONG = 0x1775; // 6005
/** EventDescriptionTooLong: Event description exceeds maximum length */
export const ENCORE_ERROR__EVENT_DESCRIPTION_TOO_LONG = 0x1776; // 6006
/** EventNameEmpty: Event name cannot be empty */
export const ENCORE_ERROR__EVENT_NAME_EMPTY = 0x1777; // 6007
/** Unauthorized: Unauthorized: signer is not the event authority */
export const ENCORE_ERROR__UNAUTHORIZED = 0x1778; // 6008
/** EventTimestampInPast: Event timestamp must be in the future */
export const ENCORE_ERROR__EVENT_TIMESTAMP_IN_PAST = 0x1779; // 6009
/** MaxSupplyReached: Maximum ticket supply reached */
export const ENCORE_ERROR__MAX_SUPPLY_REACHED = 0x177a; // 6010
/** InvalidPurchasePrice: Purchase price must be greater than zero */
export const ENCORE_ERROR__INVALID_PURCHASE_PRICE = 0x177b; // 6011
/** InvalidAddressTree: Invalid address tree */
export const ENCORE_ERROR__INVALID_ADDRESS_TREE = 0x177c; // 6012
/** InvalidTicket: Invalid ticket account */
export const ENCORE_ERROR__INVALID_TICKET = 0x177d; // 6013
/** NotTicketOwner: Seller does not own this ticket */
export const ENCORE_ERROR__NOT_TICKET_OWNER = 0x177e; // 6014
/** ExceedsResaleCap: Resale price exceeds allowed cap */
export const ENCORE_ERROR__EXCEEDS_RESALE_CAP = 0x177f; // 6015
/** TicketAlreadyTransferred: Ticket already transferred (nullifier exists) */
export const ENCORE_ERROR__TICKET_ALREADY_TRANSFERRED = 0x1780; // 6016
/** MaxTicketsPerPersonReached: Maximum tickets per person reached for this event */
export const ENCORE_ERROR__MAX_TICKETS_PER_PERSON_REACHED = 0x1781; // 6017
/** TicketAlreadySpent: Ticket has already been spent */
export const ENCORE_ERROR__TICKET_ALREADY_SPENT = 0x1782; // 6018
/** ListingNotActive: Listing not active */
export const ENCORE_ERROR__LISTING_NOT_ACTIVE = 0x1783; // 6019
/** ListingAlreadyClaimed: Listing already claimed */
export const ENCORE_ERROR__LISTING_ALREADY_CLAIMED = 0x1784; // 6020
/** ListingNotClaimed: Listing not claimed */
export const ENCORE_ERROR__LISTING_NOT_CLAIMED = 0x1785; // 6021
/** NotSeller: Not the listing seller */
export const ENCORE_ERROR__NOT_SELLER = 0x1786; // 6022
/** NotBuyer: Not the listing buyer */
export const ENCORE_ERROR__NOT_BUYER = 0x1787; // 6023
/** ClaimTimeoutNotReached: Claim timeout not reached */
export const ENCORE_ERROR__CLAIM_TIMEOUT_NOT_REACHED = 0x1788; // 6024
/** InvalidPrice: Invalid price */
export const ENCORE_ERROR__INVALID_PRICE = 0x1789; // 6025

export type EncoreError =
  | typeof ENCORE_ERROR__CLAIM_TIMEOUT_NOT_REACHED
  | typeof ENCORE_ERROR__EVENT_DESCRIPTION_TOO_LONG
  | typeof ENCORE_ERROR__EVENT_LOCATION_TOO_LONG
  | typeof ENCORE_ERROR__EVENT_NAME_EMPTY
  | typeof ENCORE_ERROR__EVENT_NAME_TOO_LONG
  | typeof ENCORE_ERROR__EVENT_TIMESTAMP_IN_PAST
  | typeof ENCORE_ERROR__EXCEEDS_RESALE_CAP
  | typeof ENCORE_ERROR__INVALID_ADDRESS_TREE
  | typeof ENCORE_ERROR__INVALID_PRICE
  | typeof ENCORE_ERROR__INVALID_PURCHASE_PRICE
  | typeof ENCORE_ERROR__INVALID_TICKET
  | typeof ENCORE_ERROR__INVALID_TICKET_SUPPLY
  | typeof ENCORE_ERROR__LISTING_ALREADY_CLAIMED
  | typeof ENCORE_ERROR__LISTING_NOT_ACTIVE
  | typeof ENCORE_ERROR__LISTING_NOT_CLAIMED
  | typeof ENCORE_ERROR__MAX_SUPPLY_REACHED
  | typeof ENCORE_ERROR__MAX_TICKETS_PER_PERSON_REACHED
  | typeof ENCORE_ERROR__NOT_BUYER
  | typeof ENCORE_ERROR__NOT_SELLER
  | typeof ENCORE_ERROR__NOT_TICKET_OWNER
  | typeof ENCORE_ERROR__RESALE_CAP_TOO_HIGH
  | typeof ENCORE_ERROR__RESALE_CAP_TOO_LOW
  | typeof ENCORE_ERROR__TICKET_ALREADY_SPENT
  | typeof ENCORE_ERROR__TICKET_ALREADY_TRANSFERRED
  | typeof ENCORE_ERROR__TICKET_SUPPLY_TOO_LARGE
  | typeof ENCORE_ERROR__UNAUTHORIZED;

let encoreErrorMessages: Record<EncoreError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  encoreErrorMessages = {
    [ENCORE_ERROR__CLAIM_TIMEOUT_NOT_REACHED]: `Claim timeout not reached`,
    [ENCORE_ERROR__EVENT_DESCRIPTION_TOO_LONG]: `Event description exceeds maximum length`,
    [ENCORE_ERROR__EVENT_LOCATION_TOO_LONG]: `Event location exceeds maximum length`,
    [ENCORE_ERROR__EVENT_NAME_EMPTY]: `Event name cannot be empty`,
    [ENCORE_ERROR__EVENT_NAME_TOO_LONG]: `Event name exceeds maximum length`,
    [ENCORE_ERROR__EVENT_TIMESTAMP_IN_PAST]: `Event timestamp must be in the future`,
    [ENCORE_ERROR__EXCEEDS_RESALE_CAP]: `Resale price exceeds allowed cap`,
    [ENCORE_ERROR__INVALID_ADDRESS_TREE]: `Invalid address tree`,
    [ENCORE_ERROR__INVALID_PRICE]: `Invalid price`,
    [ENCORE_ERROR__INVALID_PURCHASE_PRICE]: `Purchase price must be greater than zero`,
    [ENCORE_ERROR__INVALID_TICKET]: `Invalid ticket account`,
    [ENCORE_ERROR__INVALID_TICKET_SUPPLY]: `Ticket supply must be greater than zero`,
    [ENCORE_ERROR__LISTING_ALREADY_CLAIMED]: `Listing already claimed`,
    [ENCORE_ERROR__LISTING_NOT_ACTIVE]: `Listing not active`,
    [ENCORE_ERROR__LISTING_NOT_CLAIMED]: `Listing not claimed`,
    [ENCORE_ERROR__MAX_SUPPLY_REACHED]: `Maximum ticket supply reached`,
    [ENCORE_ERROR__MAX_TICKETS_PER_PERSON_REACHED]: `Maximum tickets per person reached for this event`,
    [ENCORE_ERROR__NOT_BUYER]: `Not the listing buyer`,
    [ENCORE_ERROR__NOT_SELLER]: `Not the listing seller`,
    [ENCORE_ERROR__NOT_TICKET_OWNER]: `Seller does not own this ticket`,
    [ENCORE_ERROR__RESALE_CAP_TOO_HIGH]: `Resale cap exceeds maximum allowed (10.0x)`,
    [ENCORE_ERROR__RESALE_CAP_TOO_LOW]: `Resale cap must be at least 1.0x (10000 basis points)`,
    [ENCORE_ERROR__TICKET_ALREADY_SPENT]: `Ticket has already been spent`,
    [ENCORE_ERROR__TICKET_ALREADY_TRANSFERRED]: `Ticket already transferred (nullifier exists)`,
    [ENCORE_ERROR__TICKET_SUPPLY_TOO_LARGE]: `Ticket supply exceeds maximum allowed`,
    [ENCORE_ERROR__UNAUTHORIZED]: `Unauthorized: signer is not the event authority`,
  };
}

export function getEncoreErrorMessage(code: EncoreError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (encoreErrorMessages as Record<EncoreError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isEncoreError<TProgramErrorCode extends EncoreError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    ENCORE_PROGRAM_ADDRESS,
    code
  );
}
