/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CANCEL_LISTING_DISCRIMINATOR = new Uint8Array([
  41, 183, 50, 232, 230, 233, 157, 70,
]);

export function getCancelListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CANCEL_LISTING_DISCRIMINATOR
  );
}

export type CancelListingInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountSeller extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSeller extends string
        ? WritableSignerAccount<TAccountSeller> &
            AccountSignerMeta<TAccountSeller>
        : TAccountSeller,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      ...TRemainingAccounts,
    ]
  >;

export type CancelListingInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CancelListingInstructionDataArgs = {};

export function getCancelListingInstructionDataEncoder(): FixedSizeEncoder<CancelListingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CANCEL_LISTING_DISCRIMINATOR })
  );
}

export function getCancelListingInstructionDataDecoder(): FixedSizeDecoder<CancelListingInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCancelListingInstructionDataCodec(): FixedSizeCodec<
  CancelListingInstructionDataArgs,
  CancelListingInstructionData
> {
  return combineCodec(
    getCancelListingInstructionDataEncoder(),
    getCancelListingInstructionDataDecoder()
  );
}

export type CancelListingInput<
  TAccountSeller extends string = string,
  TAccountListing extends string = string,
> = {
  /** Seller who is cancelling the listing */
  seller: TransactionSigner<TAccountSeller>;
  /** Listing being cancelled - will be closed and rent returned to seller */
  listing: Address<TAccountListing>;
};

export function getCancelListingInstruction<
  TAccountSeller extends string,
  TAccountListing extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: CancelListingInput<TAccountSeller, TAccountListing>,
  config?: { programAddress?: TProgramAddress }
): CancelListingInstruction<TProgramAddress, TAccountSeller, TAccountListing> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    listing: { value: input.listing ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.listing),
    ],
    data: getCancelListingInstructionDataEncoder().encode({}),
    programAddress,
  } as CancelListingInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountListing
  >);
}

export type ParsedCancelListingInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Seller who is cancelling the listing */
    seller: TAccountMetas[0];
    /** Listing being cancelled - will be closed and rent returned to seller */
    listing: TAccountMetas[1];
  };
  data: CancelListingInstructionData;
};

export function parseCancelListingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCancelListingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { seller: getNextAccount(), listing: getNextAccount() },
    data: getCancelListingInstructionDataDecoder().decode(instruction.data),
  };
}
