/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLAIM_LISTING_DISCRIMINATOR = new Uint8Array([
  96, 238, 149, 85, 208, 136, 248, 158,
]);

export function getClaimListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_LISTING_DISCRIMINATOR
  );
}

export type ClaimListingInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountBuyer extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountBuyer extends string
        ? WritableSignerAccount<TAccountBuyer> &
            AccountSignerMeta<TAccountBuyer>
        : TAccountBuyer,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimListingInstructionData = {
  discriminator: ReadonlyUint8Array;
  buyerCommitment: ReadonlyUint8Array;
};

export type ClaimListingInstructionDataArgs = {
  buyerCommitment: ReadonlyUint8Array;
};

export function getClaimListingInstructionDataEncoder(): FixedSizeEncoder<ClaimListingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['buyerCommitment', fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_LISTING_DISCRIMINATOR })
  );
}

export function getClaimListingInstructionDataDecoder(): FixedSizeDecoder<ClaimListingInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['buyerCommitment', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getClaimListingInstructionDataCodec(): FixedSizeCodec<
  ClaimListingInstructionDataArgs,
  ClaimListingInstructionData
> {
  return combineCodec(
    getClaimListingInstructionDataEncoder(),
    getClaimListingInstructionDataDecoder()
  );
}

export type ClaimListingInput<
  TAccountBuyer extends string = string,
  TAccountListing extends string = string,
> = {
  /** Buyer who is claiming the listing */
  buyer: TransactionSigner<TAccountBuyer>;
  /** Listing being claimed */
  listing: Address<TAccountListing>;
  buyerCommitment: ClaimListingInstructionDataArgs['buyerCommitment'];
};

export function getClaimListingInstruction<
  TAccountBuyer extends string,
  TAccountListing extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: ClaimListingInput<TAccountBuyer, TAccountListing>,
  config?: { programAddress?: TProgramAddress }
): ClaimListingInstruction<TProgramAddress, TAccountBuyer, TAccountListing> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    buyer: { value: input.buyer ?? null, isWritable: true },
    listing: { value: input.listing ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.buyer),
      getAccountMeta(accounts.listing),
    ],
    data: getClaimListingInstructionDataEncoder().encode(
      args as ClaimListingInstructionDataArgs
    ),
    programAddress,
  } as ClaimListingInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountListing
  >);
}

export type ParsedClaimListingInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Buyer who is claiming the listing */
    buyer: TAccountMetas[0];
    /** Listing being claimed */
    listing: TAccountMetas[1];
  };
  data: ClaimListingInstructionData;
};

export function parseClaimListingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClaimListingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { buyer: getNextAccount(), listing: getNextAccount() },
    data: getClaimListingInstructionDataDecoder().decode(instruction.data),
  };
}
