/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getPackedAddressTreeInfoDecoder,
  getPackedAddressTreeInfoEncoder,
  getValidityProofDecoder,
  getValidityProofEncoder,
  type PackedAddressTreeInfo,
  type PackedAddressTreeInfoArgs,
  type ValidityProof,
  type ValidityProofArgs,
} from '../types';

export const COMPLETE_SALE_DISCRIMINATOR = new Uint8Array([
  212, 87, 122, 108, 63, 103, 44, 185,
]);

export function getCompleteSaleDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    COMPLETE_SALE_DISCRIMINATOR
  );
}

export type CompleteSaleInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountSeller extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSeller extends string
        ? WritableSignerAccount<TAccountSeller> &
            AccountSignerMeta<TAccountSeller>
        : TAccountSeller,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      ...TRemainingAccounts,
    ]
  >;

export type CompleteSaleInstructionData = {
  discriminator: ReadonlyUint8Array;
  proof: ValidityProof;
  addressTreeInfo: PackedAddressTreeInfo;
  outputStateTreeIndex: number;
  newTicketAddressSeed: ReadonlyUint8Array;
  ticketBump: number;
  sellerSecret: ReadonlyUint8Array;
};

export type CompleteSaleInstructionDataArgs = {
  proof: ValidityProofArgs;
  addressTreeInfo: PackedAddressTreeInfoArgs;
  outputStateTreeIndex: number;
  newTicketAddressSeed: ReadonlyUint8Array;
  ticketBump: number;
  sellerSecret: ReadonlyUint8Array;
};

export function getCompleteSaleInstructionDataEncoder(): Encoder<CompleteSaleInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['proof', getValidityProofEncoder()],
      ['addressTreeInfo', getPackedAddressTreeInfoEncoder()],
      ['outputStateTreeIndex', getU8Encoder()],
      ['newTicketAddressSeed', fixEncoderSize(getBytesEncoder(), 32)],
      ['ticketBump', getU8Encoder()],
      ['sellerSecret', fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: COMPLETE_SALE_DISCRIMINATOR })
  );
}

export function getCompleteSaleInstructionDataDecoder(): Decoder<CompleteSaleInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['proof', getValidityProofDecoder()],
    ['addressTreeInfo', getPackedAddressTreeInfoDecoder()],
    ['outputStateTreeIndex', getU8Decoder()],
    ['newTicketAddressSeed', fixDecoderSize(getBytesDecoder(), 32)],
    ['ticketBump', getU8Decoder()],
    ['sellerSecret', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getCompleteSaleInstructionDataCodec(): Codec<
  CompleteSaleInstructionDataArgs,
  CompleteSaleInstructionData
> {
  return combineCodec(
    getCompleteSaleInstructionDataEncoder(),
    getCompleteSaleInstructionDataDecoder()
  );
}

export type CompleteSaleInput<
  TAccountSeller extends string = string,
  TAccountListing extends string = string,
> = {
  /** Seller who is completing the sale */
  seller: TransactionSigner<TAccountSeller>;
  /** Listing being completed */
  listing: Address<TAccountListing>;
  proof: CompleteSaleInstructionDataArgs['proof'];
  addressTreeInfo: CompleteSaleInstructionDataArgs['addressTreeInfo'];
  outputStateTreeIndex: CompleteSaleInstructionDataArgs['outputStateTreeIndex'];
  newTicketAddressSeed: CompleteSaleInstructionDataArgs['newTicketAddressSeed'];
  ticketBump: CompleteSaleInstructionDataArgs['ticketBump'];
  sellerSecret: CompleteSaleInstructionDataArgs['sellerSecret'];
};

export function getCompleteSaleInstruction<
  TAccountSeller extends string,
  TAccountListing extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: CompleteSaleInput<TAccountSeller, TAccountListing>,
  config?: { programAddress?: TProgramAddress }
): CompleteSaleInstruction<TProgramAddress, TAccountSeller, TAccountListing> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    listing: { value: input.listing ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.listing),
    ],
    data: getCompleteSaleInstructionDataEncoder().encode(
      args as CompleteSaleInstructionDataArgs
    ),
    programAddress,
  } as CompleteSaleInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountListing
  >);
}

export type ParsedCompleteSaleInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Seller who is completing the sale */
    seller: TAccountMetas[0];
    /** Listing being completed */
    listing: TAccountMetas[1];
  };
  data: CompleteSaleInstructionData;
};

export function parseCompleteSaleInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCompleteSaleInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { seller: getNextAccount(), listing: getNextAccount() },
    data: getCompleteSaleInstructionDataDecoder().decode(instruction.data),
  };
}
