/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_EVENT_DISCRIMINATOR = new Uint8Array([
  49, 219, 29, 203, 22, 98, 100, 87,
]);

export function getCreateEventDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_EVENT_DISCRIMINATOR
  );
}

export type CreateEventInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountEventConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountEventConfig extends string
        ? WritableAccount<TAccountEventConfig>
        : TAccountEventConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateEventInstructionData = {
  discriminator: ReadonlyUint8Array;
  maxSupply: number;
  resaleCapBps: number;
  eventName: string;
  eventLocation: string;
  eventDescription: string;
  maxTicketsPerPerson: number;
  eventTimestamp: bigint;
};

export type CreateEventInstructionDataArgs = {
  maxSupply: number;
  resaleCapBps: number;
  eventName: string;
  eventLocation: string;
  eventDescription: string;
  maxTicketsPerPerson: number;
  eventTimestamp: number | bigint;
};

export function getCreateEventInstructionDataEncoder(): Encoder<CreateEventInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['maxSupply', getU32Encoder()],
      ['resaleCapBps', getU32Encoder()],
      ['eventName', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      [
        'eventLocation',
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
      ],
      [
        'eventDescription',
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
      ],
      ['maxTicketsPerPerson', getU8Encoder()],
      ['eventTimestamp', getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_EVENT_DISCRIMINATOR })
  );
}

export function getCreateEventInstructionDataDecoder(): Decoder<CreateEventInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['maxSupply', getU32Decoder()],
    ['resaleCapBps', getU32Decoder()],
    ['eventName', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['eventLocation', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    [
      'eventDescription',
      addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder()),
    ],
    ['maxTicketsPerPerson', getU8Decoder()],
    ['eventTimestamp', getI64Decoder()],
  ]);
}

export function getCreateEventInstructionDataCodec(): Codec<
  CreateEventInstructionDataArgs,
  CreateEventInstructionData
> {
  return combineCodec(
    getCreateEventInstructionDataEncoder(),
    getCreateEventInstructionDataDecoder()
  );
}

export type CreateEventAsyncInput<
  TAccountAuthority extends string = string,
  TAccountEventConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  eventConfig?: Address<TAccountEventConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  maxSupply: CreateEventInstructionDataArgs['maxSupply'];
  resaleCapBps: CreateEventInstructionDataArgs['resaleCapBps'];
  eventName: CreateEventInstructionDataArgs['eventName'];
  eventLocation: CreateEventInstructionDataArgs['eventLocation'];
  eventDescription: CreateEventInstructionDataArgs['eventDescription'];
  maxTicketsPerPerson: CreateEventInstructionDataArgs['maxTicketsPerPerson'];
  eventTimestamp: CreateEventInstructionDataArgs['eventTimestamp'];
};

export async function getCreateEventInstructionAsync<
  TAccountAuthority extends string,
  TAccountEventConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: CreateEventAsyncInput<
    TAccountAuthority,
    TAccountEventConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateEventInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountEventConfig,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.eventConfig.value) {
    accounts.eventConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([101, 118, 101, 110, 116])),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.eventConfig),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateEventInstructionDataEncoder().encode(
      args as CreateEventInstructionDataArgs
    ),
    programAddress,
  } as CreateEventInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountEventConfig,
    TAccountSystemProgram
  >);
}

export type CreateEventInput<
  TAccountAuthority extends string = string,
  TAccountEventConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  eventConfig: Address<TAccountEventConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  maxSupply: CreateEventInstructionDataArgs['maxSupply'];
  resaleCapBps: CreateEventInstructionDataArgs['resaleCapBps'];
  eventName: CreateEventInstructionDataArgs['eventName'];
  eventLocation: CreateEventInstructionDataArgs['eventLocation'];
  eventDescription: CreateEventInstructionDataArgs['eventDescription'];
  maxTicketsPerPerson: CreateEventInstructionDataArgs['maxTicketsPerPerson'];
  eventTimestamp: CreateEventInstructionDataArgs['eventTimestamp'];
};

export function getCreateEventInstruction<
  TAccountAuthority extends string,
  TAccountEventConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: CreateEventInput<
    TAccountAuthority,
    TAccountEventConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateEventInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountEventConfig,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.eventConfig),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateEventInstructionDataEncoder().encode(
      args as CreateEventInstructionDataArgs
    ),
    programAddress,
  } as CreateEventInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountEventConfig,
    TAccountSystemProgram
  >);
}

export type ParsedCreateEventInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    eventConfig: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: CreateEventInstructionData;
};

export function parseCreateEventInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateEventInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      eventConfig: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateEventInstructionDataDecoder().decode(instruction.data),
  };
}
