/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_LISTING_DISCRIMINATOR = new Uint8Array([
  18, 168, 45, 24, 191, 31, 117, 54,
]);

export function getCreateListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_LISTING_DISCRIMINATOR
  );
}

export type CreateListingInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountSeller extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSeller extends string
        ? WritableSignerAccount<TAccountSeller> &
            AccountSignerMeta<TAccountSeller>
        : TAccountSeller,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateListingInstructionData = {
  discriminator: ReadonlyUint8Array;
  ticketCommitment: ReadonlyUint8Array;
  encryptedSecret: ReadonlyUint8Array;
  priceLamports: bigint;
  eventConfig: Address;
  ticketId: number;
  ticketAddressSeed: ReadonlyUint8Array;
  ticketBump: number;
};

export type CreateListingInstructionDataArgs = {
  ticketCommitment: ReadonlyUint8Array;
  encryptedSecret: ReadonlyUint8Array;
  priceLamports: number | bigint;
  eventConfig: Address;
  ticketId: number;
  ticketAddressSeed: ReadonlyUint8Array;
  ticketBump: number;
};

export function getCreateListingInstructionDataEncoder(): FixedSizeEncoder<CreateListingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['ticketCommitment', fixEncoderSize(getBytesEncoder(), 32)],
      ['encryptedSecret', fixEncoderSize(getBytesEncoder(), 32)],
      ['priceLamports', getU64Encoder()],
      ['eventConfig', getAddressEncoder()],
      ['ticketId', getU32Encoder()],
      ['ticketAddressSeed', fixEncoderSize(getBytesEncoder(), 32)],
      ['ticketBump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_LISTING_DISCRIMINATOR })
  );
}

export function getCreateListingInstructionDataDecoder(): FixedSizeDecoder<CreateListingInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['ticketCommitment', fixDecoderSize(getBytesDecoder(), 32)],
    ['encryptedSecret', fixDecoderSize(getBytesDecoder(), 32)],
    ['priceLamports', getU64Decoder()],
    ['eventConfig', getAddressDecoder()],
    ['ticketId', getU32Decoder()],
    ['ticketAddressSeed', fixDecoderSize(getBytesDecoder(), 32)],
    ['ticketBump', getU8Decoder()],
  ]);
}

export function getCreateListingInstructionDataCodec(): FixedSizeCodec<
  CreateListingInstructionDataArgs,
  CreateListingInstructionData
> {
  return combineCodec(
    getCreateListingInstructionDataEncoder(),
    getCreateListingInstructionDataDecoder()
  );
}

export type CreateListingAsyncInput<
  TAccountSeller extends string = string,
  TAccountListing extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Seller who is listing the ticket */
  seller: TransactionSigner<TAccountSeller>;
  /** Listing account to be created */
  listing?: Address<TAccountListing>;
  systemProgram?: Address<TAccountSystemProgram>;
  ticketCommitment: CreateListingInstructionDataArgs['ticketCommitment'];
  encryptedSecret: CreateListingInstructionDataArgs['encryptedSecret'];
  priceLamports: CreateListingInstructionDataArgs['priceLamports'];
  eventConfig: CreateListingInstructionDataArgs['eventConfig'];
  ticketId: CreateListingInstructionDataArgs['ticketId'];
  ticketAddressSeed: CreateListingInstructionDataArgs['ticketAddressSeed'];
  ticketBump: CreateListingInstructionDataArgs['ticketBump'];
};

export async function getCreateListingInstructionAsync<
  TAccountSeller extends string,
  TAccountListing extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: CreateListingAsyncInput<
    TAccountSeller,
    TAccountListing,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateListingInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountListing,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    listing: { value: input.listing ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.listing.value) {
    accounts.listing.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([108, 105, 115, 116, 105, 110, 103])
        ),
        getAddressEncoder().encode(expectAddress(accounts.seller.value)),
        fixEncoderSize(getBytesEncoder(), 32).encode(
          expectSome(args.ticketCommitment)
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.listing),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateListingInstructionDataEncoder().encode(
      args as CreateListingInstructionDataArgs
    ),
    programAddress,
  } as CreateListingInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountListing,
    TAccountSystemProgram
  >);
}

export type CreateListingInput<
  TAccountSeller extends string = string,
  TAccountListing extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Seller who is listing the ticket */
  seller: TransactionSigner<TAccountSeller>;
  /** Listing account to be created */
  listing: Address<TAccountListing>;
  systemProgram?: Address<TAccountSystemProgram>;
  ticketCommitment: CreateListingInstructionDataArgs['ticketCommitment'];
  encryptedSecret: CreateListingInstructionDataArgs['encryptedSecret'];
  priceLamports: CreateListingInstructionDataArgs['priceLamports'];
  eventConfig: CreateListingInstructionDataArgs['eventConfig'];
  ticketId: CreateListingInstructionDataArgs['ticketId'];
  ticketAddressSeed: CreateListingInstructionDataArgs['ticketAddressSeed'];
  ticketBump: CreateListingInstructionDataArgs['ticketBump'];
};

export function getCreateListingInstruction<
  TAccountSeller extends string,
  TAccountListing extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: CreateListingInput<
    TAccountSeller,
    TAccountListing,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateListingInstruction<
  TProgramAddress,
  TAccountSeller,
  TAccountListing,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    listing: { value: input.listing ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.listing),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateListingInstructionDataEncoder().encode(
      args as CreateListingInstructionDataArgs
    ),
    programAddress,
  } as CreateListingInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountListing,
    TAccountSystemProgram
  >);
}

export type ParsedCreateListingInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Seller who is listing the ticket */
    seller: TAccountMetas[0];
    /** Listing account to be created */
    listing: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: CreateListingInstructionData;
};

export function parseCreateListingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateListingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      seller: getNextAccount(),
      listing: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateListingInstructionDataDecoder().decode(instruction.data),
  };
}
