/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';
import {
  getPackedAddressTreeInfoDecoder,
  getPackedAddressTreeInfoEncoder,
  getValidityProofDecoder,
  getValidityProofEncoder,
  type PackedAddressTreeInfo,
  type PackedAddressTreeInfoArgs,
  type ValidityProof,
  type ValidityProofArgs,
} from '../types';

export const MINT_TICKET_DISCRIMINATOR = new Uint8Array([
  159, 167, 223, 60, 138, 6, 23, 29,
]);

export function getMintTicketDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MINT_TICKET_DISCRIMINATOR);
}

export type MintTicketInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountBuyer extends string | AccountMeta<string> = string,
  TAccountEventOwner extends string | AccountMeta<string> = string,
  TAccountEventConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountBuyer extends string
        ? WritableSignerAccount<TAccountBuyer> &
            AccountSignerMeta<TAccountBuyer>
        : TAccountBuyer,
      TAccountEventOwner extends string
        ? ReadonlyAccount<TAccountEventOwner>
        : TAccountEventOwner,
      TAccountEventConfig extends string
        ? WritableAccount<TAccountEventConfig>
        : TAccountEventConfig,
      ...TRemainingAccounts,
    ]
  >;

export type MintTicketInstructionData = {
  discriminator: ReadonlyUint8Array;
  proof: ValidityProof;
  addressTreeInfo: PackedAddressTreeInfo;
  outputStateTreeIndex: number;
  ownerCommitment: ReadonlyUint8Array;
  purchasePrice: bigint;
  ticketAddressSeed: ReadonlyUint8Array;
};

export type MintTicketInstructionDataArgs = {
  proof: ValidityProofArgs;
  addressTreeInfo: PackedAddressTreeInfoArgs;
  outputStateTreeIndex: number;
  ownerCommitment: ReadonlyUint8Array;
  purchasePrice: number | bigint;
  ticketAddressSeed: ReadonlyUint8Array;
};

export function getMintTicketInstructionDataEncoder(): Encoder<MintTicketInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['proof', getValidityProofEncoder()],
      ['addressTreeInfo', getPackedAddressTreeInfoEncoder()],
      ['outputStateTreeIndex', getU8Encoder()],
      ['ownerCommitment', fixEncoderSize(getBytesEncoder(), 32)],
      ['purchasePrice', getU64Encoder()],
      ['ticketAddressSeed', fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: MINT_TICKET_DISCRIMINATOR })
  );
}

export function getMintTicketInstructionDataDecoder(): Decoder<MintTicketInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['proof', getValidityProofDecoder()],
    ['addressTreeInfo', getPackedAddressTreeInfoDecoder()],
    ['outputStateTreeIndex', getU8Decoder()],
    ['ownerCommitment', fixDecoderSize(getBytesDecoder(), 32)],
    ['purchasePrice', getU64Decoder()],
    ['ticketAddressSeed', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getMintTicketInstructionDataCodec(): Codec<
  MintTicketInstructionDataArgs,
  MintTicketInstructionData
> {
  return combineCodec(
    getMintTicketInstructionDataEncoder(),
    getMintTicketInstructionDataDecoder()
  );
}

export type MintTicketAsyncInput<
  TAccountBuyer extends string = string,
  TAccountEventOwner extends string = string,
  TAccountEventConfig extends string = string,
> = {
  /** The buyer who is purchasing the ticket */
  buyer: TransactionSigner<TAccountBuyer>;
  eventOwner: Address<TAccountEventOwner>;
  eventConfig?: Address<TAccountEventConfig>;
  proof: MintTicketInstructionDataArgs['proof'];
  addressTreeInfo: MintTicketInstructionDataArgs['addressTreeInfo'];
  outputStateTreeIndex: MintTicketInstructionDataArgs['outputStateTreeIndex'];
  ownerCommitment: MintTicketInstructionDataArgs['ownerCommitment'];
  purchasePrice: MintTicketInstructionDataArgs['purchasePrice'];
  ticketAddressSeed: MintTicketInstructionDataArgs['ticketAddressSeed'];
};

export async function getMintTicketInstructionAsync<
  TAccountBuyer extends string,
  TAccountEventOwner extends string,
  TAccountEventConfig extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: MintTicketAsyncInput<
    TAccountBuyer,
    TAccountEventOwner,
    TAccountEventConfig
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  MintTicketInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountEventOwner,
    TAccountEventConfig
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    buyer: { value: input.buyer ?? null, isWritable: true },
    eventOwner: { value: input.eventOwner ?? null, isWritable: false },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.eventConfig.value) {
    accounts.eventConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([101, 118, 101, 110, 116])),
        getAddressEncoder().encode(expectAddress(accounts.eventOwner.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.buyer),
      getAccountMeta(accounts.eventOwner),
      getAccountMeta(accounts.eventConfig),
    ],
    data: getMintTicketInstructionDataEncoder().encode(
      args as MintTicketInstructionDataArgs
    ),
    programAddress,
  } as MintTicketInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountEventOwner,
    TAccountEventConfig
  >);
}

export type MintTicketInput<
  TAccountBuyer extends string = string,
  TAccountEventOwner extends string = string,
  TAccountEventConfig extends string = string,
> = {
  /** The buyer who is purchasing the ticket */
  buyer: TransactionSigner<TAccountBuyer>;
  eventOwner: Address<TAccountEventOwner>;
  eventConfig: Address<TAccountEventConfig>;
  proof: MintTicketInstructionDataArgs['proof'];
  addressTreeInfo: MintTicketInstructionDataArgs['addressTreeInfo'];
  outputStateTreeIndex: MintTicketInstructionDataArgs['outputStateTreeIndex'];
  ownerCommitment: MintTicketInstructionDataArgs['ownerCommitment'];
  purchasePrice: MintTicketInstructionDataArgs['purchasePrice'];
  ticketAddressSeed: MintTicketInstructionDataArgs['ticketAddressSeed'];
};

export function getMintTicketInstruction<
  TAccountBuyer extends string,
  TAccountEventOwner extends string,
  TAccountEventConfig extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: MintTicketInput<
    TAccountBuyer,
    TAccountEventOwner,
    TAccountEventConfig
  >,
  config?: { programAddress?: TProgramAddress }
): MintTicketInstruction<
  TProgramAddress,
  TAccountBuyer,
  TAccountEventOwner,
  TAccountEventConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    buyer: { value: input.buyer ?? null, isWritable: true },
    eventOwner: { value: input.eventOwner ?? null, isWritable: false },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.buyer),
      getAccountMeta(accounts.eventOwner),
      getAccountMeta(accounts.eventConfig),
    ],
    data: getMintTicketInstructionDataEncoder().encode(
      args as MintTicketInstructionDataArgs
    ),
    programAddress,
  } as MintTicketInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountEventOwner,
    TAccountEventConfig
  >);
}

export type ParsedMintTicketInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The buyer who is purchasing the ticket */
    buyer: TAccountMetas[0];
    eventOwner: TAccountMetas[1];
    eventConfig: TAccountMetas[2];
  };
  data: MintTicketInstructionData;
};

export function parseMintTicketInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedMintTicketInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      buyer: getNextAccount(),
      eventOwner: getNextAccount(),
      eventConfig: getNextAccount(),
    },
    data: getMintTicketInstructionDataDecoder().decode(instruction.data),
  };
}
