/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RELEASE_CLAIM_DISCRIMINATOR = new Uint8Array([
  109, 194, 80, 47, 30, 93, 16, 253,
]);

export function getReleaseClaimDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RELEASE_CLAIM_DISCRIMINATOR
  );
}

export type ReleaseClaimInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountSeller extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSeller extends string
        ? WritableSignerAccount<TAccountSeller> &
            AccountSignerMeta<TAccountSeller>
        : TAccountSeller,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      ...TRemainingAccounts,
    ]
  >;

export type ReleaseClaimInstructionData = { discriminator: ReadonlyUint8Array };

export type ReleaseClaimInstructionDataArgs = {};

export function getReleaseClaimInstructionDataEncoder(): FixedSizeEncoder<ReleaseClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: RELEASE_CLAIM_DISCRIMINATOR })
  );
}

export function getReleaseClaimInstructionDataDecoder(): FixedSizeDecoder<ReleaseClaimInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getReleaseClaimInstructionDataCodec(): FixedSizeCodec<
  ReleaseClaimInstructionDataArgs,
  ReleaseClaimInstructionData
> {
  return combineCodec(
    getReleaseClaimInstructionDataEncoder(),
    getReleaseClaimInstructionDataDecoder()
  );
}

export type ReleaseClaimInput<
  TAccountSeller extends string = string,
  TAccountListing extends string = string,
> = {
  /** Seller who is releasing the claim */
  seller: TransactionSigner<TAccountSeller>;
  /** Listing being released */
  listing: Address<TAccountListing>;
};

export function getReleaseClaimInstruction<
  TAccountSeller extends string,
  TAccountListing extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: ReleaseClaimInput<TAccountSeller, TAccountListing>,
  config?: { programAddress?: TProgramAddress }
): ReleaseClaimInstruction<TProgramAddress, TAccountSeller, TAccountListing> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    listing: { value: input.listing ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.listing),
    ],
    data: getReleaseClaimInstructionDataEncoder().encode({}),
    programAddress,
  } as ReleaseClaimInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountListing
  >);
}

export type ParsedReleaseClaimInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Seller who is releasing the claim */
    seller: TAccountMetas[0];
    /** Listing being released */
    listing: TAccountMetas[1];
  };
  data: ReleaseClaimInstructionData;
};

export function parseReleaseClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedReleaseClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { seller: getNextAccount(), listing: getNextAccount() },
    data: getReleaseClaimInstructionDataDecoder().decode(instruction.data),
  };
}
