/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';
import {
  getPackedAddressTreeInfoDecoder,
  getPackedAddressTreeInfoEncoder,
  getValidityProofDecoder,
  getValidityProofEncoder,
  type PackedAddressTreeInfo,
  type PackedAddressTreeInfoArgs,
  type ValidityProof,
  type ValidityProofArgs,
} from '../types';

export const TRANSFER_TICKET_DISCRIMINATOR = new Uint8Array([
  191, 184, 74, 239, 164, 172, 188, 32,
]);

export function getTransferTicketDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_TICKET_DISCRIMINATOR
  );
}

export type TransferTicketInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountSeller extends string | AccountMeta<string> = string,
  TAccountEventOwner extends string | AccountMeta<string> = string,
  TAccountEventConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSeller extends string
        ? WritableSignerAccount<TAccountSeller> &
            AccountSignerMeta<TAccountSeller>
        : TAccountSeller,
      TAccountEventOwner extends string
        ? ReadonlyAccount<TAccountEventOwner>
        : TAccountEventOwner,
      TAccountEventConfig extends string
        ? WritableAccount<TAccountEventConfig>
        : TAccountEventConfig,
      ...TRemainingAccounts,
    ]
  >;

export type TransferTicketInstructionData = {
  discriminator: ReadonlyUint8Array;
  proof: ValidityProof;
  addressTreeInfo: PackedAddressTreeInfo;
  outputStateTreeIndex: number;
  currentTicketId: number;
  currentOriginalPrice: bigint;
  sellerSecret: ReadonlyUint8Array;
  newOwnerCommitment: ReadonlyUint8Array;
  newTicketAddressSeed: ReadonlyUint8Array;
  resalePrice: Option<bigint>;
};

export type TransferTicketInstructionDataArgs = {
  proof: ValidityProofArgs;
  addressTreeInfo: PackedAddressTreeInfoArgs;
  outputStateTreeIndex: number;
  currentTicketId: number;
  currentOriginalPrice: number | bigint;
  sellerSecret: ReadonlyUint8Array;
  newOwnerCommitment: ReadonlyUint8Array;
  newTicketAddressSeed: ReadonlyUint8Array;
  resalePrice: OptionOrNullable<number | bigint>;
};

export function getTransferTicketInstructionDataEncoder(): Encoder<TransferTicketInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['proof', getValidityProofEncoder()],
      ['addressTreeInfo', getPackedAddressTreeInfoEncoder()],
      ['outputStateTreeIndex', getU8Encoder()],
      ['currentTicketId', getU32Encoder()],
      ['currentOriginalPrice', getU64Encoder()],
      ['sellerSecret', fixEncoderSize(getBytesEncoder(), 32)],
      ['newOwnerCommitment', fixEncoderSize(getBytesEncoder(), 32)],
      ['newTicketAddressSeed', fixEncoderSize(getBytesEncoder(), 32)],
      ['resalePrice', getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_TICKET_DISCRIMINATOR })
  );
}

export function getTransferTicketInstructionDataDecoder(): Decoder<TransferTicketInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['proof', getValidityProofDecoder()],
    ['addressTreeInfo', getPackedAddressTreeInfoDecoder()],
    ['outputStateTreeIndex', getU8Decoder()],
    ['currentTicketId', getU32Decoder()],
    ['currentOriginalPrice', getU64Decoder()],
    ['sellerSecret', fixDecoderSize(getBytesDecoder(), 32)],
    ['newOwnerCommitment', fixDecoderSize(getBytesDecoder(), 32)],
    ['newTicketAddressSeed', fixDecoderSize(getBytesDecoder(), 32)],
    ['resalePrice', getOptionDecoder(getU64Decoder())],
  ]);
}

export function getTransferTicketInstructionDataCodec(): Codec<
  TransferTicketInstructionDataArgs,
  TransferTicketInstructionData
> {
  return combineCodec(
    getTransferTicketInstructionDataEncoder(),
    getTransferTicketInstructionDataDecoder()
  );
}

export type TransferTicketAsyncInput<
  TAccountSeller extends string = string,
  TAccountEventOwner extends string = string,
  TAccountEventConfig extends string = string,
> = {
  /** The seller who is transferring (also pays fees) */
  seller: TransactionSigner<TAccountSeller>;
  eventOwner: Address<TAccountEventOwner>;
  /** Event config to check resale cap */
  eventConfig?: Address<TAccountEventConfig>;
  proof: TransferTicketInstructionDataArgs['proof'];
  addressTreeInfo: TransferTicketInstructionDataArgs['addressTreeInfo'];
  outputStateTreeIndex: TransferTicketInstructionDataArgs['outputStateTreeIndex'];
  currentTicketId: TransferTicketInstructionDataArgs['currentTicketId'];
  currentOriginalPrice: TransferTicketInstructionDataArgs['currentOriginalPrice'];
  sellerSecret: TransferTicketInstructionDataArgs['sellerSecret'];
  newOwnerCommitment: TransferTicketInstructionDataArgs['newOwnerCommitment'];
  newTicketAddressSeed: TransferTicketInstructionDataArgs['newTicketAddressSeed'];
  resalePrice: TransferTicketInstructionDataArgs['resalePrice'];
};

export async function getTransferTicketInstructionAsync<
  TAccountSeller extends string,
  TAccountEventOwner extends string,
  TAccountEventConfig extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: TransferTicketAsyncInput<
    TAccountSeller,
    TAccountEventOwner,
    TAccountEventConfig
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  TransferTicketInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountEventOwner,
    TAccountEventConfig
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    eventOwner: { value: input.eventOwner ?? null, isWritable: false },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.eventConfig.value) {
    accounts.eventConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([101, 118, 101, 110, 116])),
        getAddressEncoder().encode(expectAddress(accounts.eventOwner.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.eventOwner),
      getAccountMeta(accounts.eventConfig),
    ],
    data: getTransferTicketInstructionDataEncoder().encode(
      args as TransferTicketInstructionDataArgs
    ),
    programAddress,
  } as TransferTicketInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountEventOwner,
    TAccountEventConfig
  >);
}

export type TransferTicketInput<
  TAccountSeller extends string = string,
  TAccountEventOwner extends string = string,
  TAccountEventConfig extends string = string,
> = {
  /** The seller who is transferring (also pays fees) */
  seller: TransactionSigner<TAccountSeller>;
  eventOwner: Address<TAccountEventOwner>;
  /** Event config to check resale cap */
  eventConfig: Address<TAccountEventConfig>;
  proof: TransferTicketInstructionDataArgs['proof'];
  addressTreeInfo: TransferTicketInstructionDataArgs['addressTreeInfo'];
  outputStateTreeIndex: TransferTicketInstructionDataArgs['outputStateTreeIndex'];
  currentTicketId: TransferTicketInstructionDataArgs['currentTicketId'];
  currentOriginalPrice: TransferTicketInstructionDataArgs['currentOriginalPrice'];
  sellerSecret: TransferTicketInstructionDataArgs['sellerSecret'];
  newOwnerCommitment: TransferTicketInstructionDataArgs['newOwnerCommitment'];
  newTicketAddressSeed: TransferTicketInstructionDataArgs['newTicketAddressSeed'];
  resalePrice: TransferTicketInstructionDataArgs['resalePrice'];
};

export function getTransferTicketInstruction<
  TAccountSeller extends string,
  TAccountEventOwner extends string,
  TAccountEventConfig extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: TransferTicketInput<
    TAccountSeller,
    TAccountEventOwner,
    TAccountEventConfig
  >,
  config?: { programAddress?: TProgramAddress }
): TransferTicketInstruction<
  TProgramAddress,
  TAccountSeller,
  TAccountEventOwner,
  TAccountEventConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    seller: { value: input.seller ?? null, isWritable: true },
    eventOwner: { value: input.eventOwner ?? null, isWritable: false },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.eventOwner),
      getAccountMeta(accounts.eventConfig),
    ],
    data: getTransferTicketInstructionDataEncoder().encode(
      args as TransferTicketInstructionDataArgs
    ),
    programAddress,
  } as TransferTicketInstruction<
    TProgramAddress,
    TAccountSeller,
    TAccountEventOwner,
    TAccountEventConfig
  >);
}

export type ParsedTransferTicketInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The seller who is transferring (also pays fees) */
    seller: TAccountMetas[0];
    eventOwner: TAccountMetas[1];
    /** Event config to check resale cap */
    eventConfig: TAccountMetas[2];
  };
  data: TransferTicketInstructionData;
};

export function parseTransferTicketInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedTransferTicketInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      seller: getNextAccount(),
      eventOwner: getNextAccount(),
      eventConfig: getNextAccount(),
    },
    data: getTransferTicketInstructionDataDecoder().decode(instruction.data),
  };
}
