/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { ENCORE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const UPDATE_EVENT_DISCRIMINATOR = new Uint8Array([
  70, 108, 211, 125, 171, 176, 25, 217,
]);

export function getUpdateEventDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_EVENT_DISCRIMINATOR
  );
}

export type UpdateEventInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountEventConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountEventConfig extends string
        ? WritableAccount<TAccountEventConfig>
        : TAccountEventConfig,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateEventInstructionData = {
  discriminator: ReadonlyUint8Array;
  resaleCapBps: Option<number>;
};

export type UpdateEventInstructionDataArgs = {
  resaleCapBps: OptionOrNullable<number>;
};

export function getUpdateEventInstructionDataEncoder(): Encoder<UpdateEventInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['resaleCapBps', getOptionEncoder(getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_EVENT_DISCRIMINATOR })
  );
}

export function getUpdateEventInstructionDataDecoder(): Decoder<UpdateEventInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['resaleCapBps', getOptionDecoder(getU32Decoder())],
  ]);
}

export function getUpdateEventInstructionDataCodec(): Codec<
  UpdateEventInstructionDataArgs,
  UpdateEventInstructionData
> {
  return combineCodec(
    getUpdateEventInstructionDataEncoder(),
    getUpdateEventInstructionDataDecoder()
  );
}

export type UpdateEventAsyncInput<
  TAccountAuthority extends string = string,
  TAccountEventConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  eventConfig?: Address<TAccountEventConfig>;
  resaleCapBps: UpdateEventInstructionDataArgs['resaleCapBps'];
};

export async function getUpdateEventInstructionAsync<
  TAccountAuthority extends string,
  TAccountEventConfig extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: UpdateEventAsyncInput<TAccountAuthority, TAccountEventConfig>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateEventInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountEventConfig
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.eventConfig.value) {
    accounts.eventConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([101, 118, 101, 110, 116])),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.eventConfig),
    ],
    data: getUpdateEventInstructionDataEncoder().encode(
      args as UpdateEventInstructionDataArgs
    ),
    programAddress,
  } as UpdateEventInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountEventConfig
  >);
}

export type UpdateEventInput<
  TAccountAuthority extends string = string,
  TAccountEventConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  eventConfig: Address<TAccountEventConfig>;
  resaleCapBps: UpdateEventInstructionDataArgs['resaleCapBps'];
};

export function getUpdateEventInstruction<
  TAccountAuthority extends string,
  TAccountEventConfig extends string,
  TProgramAddress extends Address = typeof ENCORE_PROGRAM_ADDRESS,
>(
  input: UpdateEventInput<TAccountAuthority, TAccountEventConfig>,
  config?: { programAddress?: TProgramAddress }
): UpdateEventInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountEventConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? ENCORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    eventConfig: { value: input.eventConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.eventConfig),
    ],
    data: getUpdateEventInstructionDataEncoder().encode(
      args as UpdateEventInstructionDataArgs
    ),
    programAddress,
  } as UpdateEventInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountEventConfig
  >);
}

export type ParsedUpdateEventInstruction<
  TProgram extends string = typeof ENCORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    eventConfig: TAccountMetas[1];
  };
  data: UpdateEventInstructionData;
};

export function parseUpdateEventInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateEventInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { authority: getNextAccount(), eventConfig: getNextAccount() },
    data: getUpdateEventInstructionDataDecoder().decode(instruction.data),
  };
}
